name: DevSecOps CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check
      
    - name: Rename JAR to app.jar
      run: mv target/*.jar target/app.jar

    - name: Docker Build
      run: docker build -t sushma-0209/wiprodsc1 .

    - name: Docker Scan
      run: docker scan sushma-0209/wiprodsc1
